trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:

# 1. Restore
- task: DotNetCoreCLI@2
  displayName: 'Restore'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

# 2. Build
- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

# 3. Publish
- task: DotNetCoreCLI@2
  displayName: 'Publish'
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

# 4. Deploy to Azure App Service
- task: AzureWebApp@1
  displayName: 'Deploy to App Service'
  inputs:
    azureSubscription: 'GymMembership'
    appName: 'gym-membership-webapp'
    package: '$(Build.ArtifactStagingDirectory)/**/*.zip'

# 5. Fetch connection string from App Service
- task: AzureCLI@2
  displayName: 'Fetch connection string'
  inputs:
    azureSubscription: 'GymMembership'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      $conn = az webapp config connection-string list `
        --name gym-membership-webapp `
        --resource-group ResourceGroup1 `
        --query "[?name=='DefaultConnection'].value" -o tsv

      echo "##vso[task.setvariable variable=DefaultConnection;issecret=true]$conn"

# 6. Install dotnet-ef
- task: DotNetCoreCLI@2
  displayName: 'Install dotnet-ef'
  inputs:
    command: 'custom'
    custom: 'tool'
    arguments: 'install --global dotnet-ef'
  env:
    PATH: $(PATH):$(Agent.ToolsDirectory)/dotnet/tools


# 7. Run EF Core migrations
- task: DotNetCoreCLI@2
  displayName: 'Run EF Core Migrations'
  inputs:
    command: 'custom'
    custom: 'ef'
    arguments: >
      database update
      --project GymMembers/src/GymMembers.csproj
      --startup-project GymMembers/src/GymMembers.csproj
      --connection "$(DefaultConnection)"