// <auto-generated />
using System;
using GymMembers.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GymMembers.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GymMemberClassSession", b =>
                {
                    b.Property<int>("GymMemberId")
                        .HasColumnType("int");

                    b.Property<int>("ClassSessionId")
                        .HasColumnType("int");

                    b.HasKey("GymMemberId", "ClassSessionId");

                    b.HasIndex("ClassSessionId");

                    b.ToTable("GymMemberClassSession", (string)null);

                    b.HasData(
                        new
                        {
                            GymMemberId = 1,
                            ClassSessionId = 1
                        },
                        new
                        {
                            GymMemberId = 1,
                            ClassSessionId = 2
                        },
                        new
                        {
                            GymMemberId = 2,
                            ClassSessionId = 2
                        },
                        new
                        {
                            GymMemberId = 3,
                            ClassSessionId = 3
                        });
                });

            modelBuilder.Entity("GymMembers.Models.ClassSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ClassSessions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 20,
                            Name = "Morning Yoga",
                            StartTime = new DateTime(2024, 6, 1, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 15,
                            Name = "HIIT Blast",
                            StartTime = new DateTime(2024, 6, 1, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 25,
                            Name = "Spin Class",
                            StartTime = new DateTime(2024, 6, 2, 7, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("GymMembers.Models.GymMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("GymMembers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Alice",
                            JoinDate = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Bob",
                            JoinDate = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Charlie",
                            JoinDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Brown"
                        });
                });

            modelBuilder.Entity("GymMemberClassSession", b =>
                {
                    b.HasOne("GymMembers.Models.ClassSession", null)
                        .WithMany()
                        .HasForeignKey("ClassSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_GymMemberClassSession_ClassSession");

                    b.HasOne("GymMembers.Models.GymMember", null)
                        .WithMany()
                        .HasForeignKey("GymMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_GymMemberClassSession_GymMember");
                });
#pragma warning restore 612, 618
        }
    }
}
